version: 2
allowlist:
  description: Test/legacy fixtures with fake tokens
  paths:
    - legacy_intake/fixtures/**
    - DataHunter_Credentials/**
  regexes:
    - 'AIzaSy[0-9A-Za-z\-_]{20,}'
    - 'sk_(live|test)_[0-9A-Za-z]{20,}'
    - 'https://hooks\.slack\.com/services/[A-Za-z0-9/_-]+'
