version: '3.4'

services:
  bardirectoryrecon:
    # Debug configuration for VS Code Python debugging
    image: bardirectoryrecon
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 src/universal_recon.py"]
    ports:
      - 5678:5678  # Debug port
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      # Mount source code for live debugging
      - .:/app
    # Don't restart in debug mode
    restart: "no"
