version: '3.9'
services:
  python-scraper:
    image: python:3.11
    volumes:
      - ./src:/app
    working_dir: /app
    command: tail -f /dev/null  # Replace with 'python main.py' to run main
    tty: true

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leads
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
