name: verify-scripts
on:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: manual-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
