name: Bug report
description: Report a bug with clear repro steps.
labels: ["bug","priority: p2"]
body:
  - type: textarea
    attributes:
      label: Summary
      description: What happened? What did you expect?
  - type: textarea
    attributes:
      label: Reproduction
      description: Steps + commands + sample data if possible
  - type: textarea
    attributes:
      label: Logs/Traceback
      description: Paste relevant output
