name: User feedback
description: Share feedback about the CLI or docs.
labels: ["type: docs","area: cli"]
body:
  - type: textarea
    attributes:
      label: What worked well?
      description: Tell us briefly
  - type: textarea
    attributes:
      label: What was confusing?
      description: Commands, docs, or setup?
  - type: textarea
    attributes:
      label: Suggestions
      description: What would make this easier?
