name: 'Workflow Guard'
description: 'Detect workflow-only changes to short-circuit expensive CI operations'
outputs:
  attic_only:
    description: 'true if changes are workflow-only, false otherwise'
    value: ${{ steps.detect.outputs.attic_only }}
runs:
  using: 'composite'
  steps:
    - name: Fetch base branch
      shell: bash
      run: git fetch origin main --depth=1
    
    - name: Detect workflow-only change
      id: detect
      shell: bash
      run: |
        set -e
        CHANGED=$(git diff --name-only origin/main...HEAD | tr -d '\r')
        
        # If no changes, consider it workflow-only (edge case)
        if [ -z "$CHANGED" ]; then
          echo "attic_only=true" >> $GITHUB_OUTPUT
          echo "â„¹ï¸ No changes detected"
          exit 0
        fi
        
        # Check if all changes are in the allow-list
        NON_WF=$(echo "$CHANGED" | grep -Ev '^\.github/(workflows/|dependabot\.yml$)' || true)
        
        if [ -z "$NON_WF" ]; then
          echo "attic_only=true" >> $GITHUB_OUTPUT
          echo "âœ… Workflow-only change detected"
          echo "Changed files:"
          echo "$CHANGED" | sed 's/^/  - /'
        else
          echo "attic_only=false" >> $GITHUB_OUTPUT
          echo "ðŸ”„ Full CI required (non-workflow changes detected)"
          echo "Non-workflow files:"
          echo "$NON_WF" | sed 's/^/  - /'
        fi
        
        # Special handling for Dependabot
        if [ "${{ github.actor }}" = "dependabot[bot]" ]; then
          if [ -z "$NON_WF" ]; then
            echo "attic_only=true" >> $GITHUB_OUTPUT
            echo "ðŸ¤– Dependabot workflow-only change confirmed"
          fi
        fi