version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

  audit_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/audit.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

loggers:
  automation:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false

  security:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false

  audit:
    level: INFO
    handlers: [audit_file_handler]
    propagate: false

root:
  level: INFO
  handlers: [console, file_handler, error_file_handler]
