# Archived original moved to workflows_archive/ci.yml
name: archived-ci
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo "Archived original moved to workflows_archive/ci.yml"
