# Archived original moved to workflows_archive/verify-scripts.yml
name: archived-verify-scripts
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo "Archived original moved to workflows_archive/verify-scripts.yml"
