# Minimal placeholder validation rules for the CLI demo.
rules:
  - field: full_name
    require: true
    message: Name must be present.
  - field: bar_id
    require: true
    message: Bar identifier must be present.
  - field: status
    allowed:
      - active
      - inactive
      - pending
    message: Status must be one of the allowed values.
