# Minimal placeholder schema for the CLI demo.
fields:
  - name: full_name
    type: string
    description: Fully qualified name of the professional.
  - name: bar_id
    type: string
    description: Unique bar registration identifier.
  - name: status
    type: string
    description: Registration status label (active, inactive, etc.).
