# Universal Runner Configuration Template
# ==========================================
# This template shows how to use environment variables in your configuration.
# Copy this to config.yaml and customize as needed.

# Environment variable examples:
# Set these in your .env file or system environment:
# AUTOMATION_DISCORD_WEBHOOK=https://discord.com/api/webhooks/...
# AUTOMATION_EMAIL_ENABLED=true
# AUTOMATION_EMAIL_USERNAME=your-email@gmail.com
# AUTOMATION_EMAIL_PASSWORD=your-app-password

schedules:
  scraping:
    frequency: daily
    time: "02:00"
  validation:
    frequency: daily
    time: "06:00"
  export:
    frequency: weekly
    time: "23:00"
    day: sunday
  dashboard_update:
    frequency: hourly
  list_discovery:
    frequency: hourly

monitoring:
  input_directories:
    - "input/"
    - "snapshots/"
  file_patterns:
    - "*.json"
    - "*.csv"
    - "*.html"
  auto_process: true
  batch_delay: 300

notifications:
  # Use environment variable for security
  discord_webhook: "${AUTOMATION_DISCORD_WEBHOOK:}"

  email:
    enabled: ${AUTOMATION_EMAIL_ENABLED:false}
    smtp_server: "${AUTOMATION_EMAIL_SMTP_SERVER:smtp.gmail.com}"
    smtp_port: ${AUTOMATION_EMAIL_SMTP_PORT:587}
    username: "${AUTOMATION_EMAIL_USERNAME:}"
    password: "${AUTOMATION_EMAIL_PASSWORD:}"
    recipients:
      - "${AUTOMATION_EMAIL_RECIPIENT1:}"
      - "${AUTOMATION_EMAIL_RECIPIENT2:}"

dashboard:
  google_sheets:
    enabled: ${AUTOMATION_GOOGLE_SHEETS_ENABLED:false}
    spreadsheet_id: "${AUTOMATION_GOOGLE_SHEETS_ID:}"
    credentials_path: "${AUTOMATION_GOOGLE_SHEETS_CREDENTIALS:}"

  local_html:
    enabled: true
    output_path: "output/dashboard.html"

pipeline:
  sites:
    - "${AUTOMATION_SITE1:example-bar.com}"
    - "${AUTOMATION_SITE2:another-bar.com}"

  default_flags:
    - "--schema-matrix"
    - "--emit-status"
    - "--emit-drift-dashboard"

  timeout: ${AUTOMATION_PIPELINE_TIMEOUT:3600}
  retry_count: ${AUTOMATION_PIPELINE_RETRIES:3}
