name: _python-reusable
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: false
        type: string
        default: "3.11"
      run-precommit:
        required: false
        type: boolean
        default: true
      run-fast-tests:
        required: false
        type: boolean
        default: true
    secrets: {}
jobs:
  python-job:
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs['python-version'] }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt
      - name: Install deps (lockfile + editable)
        shell: bash
        run: |
          python -m pip install -U pip
          if test -f requirements-lock.txt; then
            pip install -r requirements-lock.txt
            pip install -e .
          else
            pip install -e .
          fi
      - name: Pre-commit (all)
        if: ${{ inputs['run-precommit'] }}
        shell: bash
        run: pre-commit run -a || true
      - name: Fast pytest subset (markers)
        if: ${{ inputs['run-fast-tests'] }}
        shell: bash
        run: python -m pytest -p no:cacheprovider -o addopts="" -m "not slow and not e2e and not integration" -q