name: _python-reusable
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: false
        type: string
        default: "3.11"
      diag:
        required: false
        type: boolean
        default: false
      run-precommit:
        required: false
        type: boolean
        default: true
      run-fast-tests:
        required: false
        type: boolean
        default: true
    secrets: {}
jobs:
  python-job:
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Diagnostics (python/pip/pytest)
        if: ${{ inputs['diag'] }}
        shell: bash
        run: |
          echo "--- python and pip"
          python -V || true
          python -c "import sys; print('executable:', sys.executable)" || true
          which python || which python3 || echo "no which for python"
          python -m pip --version || true
          python -m pip list --format=columns | sed -n '1,80p' || true
          python -c "import importlib.util as iu; print('pytest spec:', iu.find_spec('pytest'))" || true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs['python-version'] }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt
      - name: Install deps (lockfile + editable)
        shell: bash
        run: |
          python -m pip install -U pip
          if test -f requirements-lock.txt; then
            python -m pip install -r requirements-lock.txt
            python -m pip install -e .
          else
            python -m pip install -e .
          fi
      - name: Pre-commit (all)
        if: ${{ inputs['run-precommit'] }}
        shell: bash
        run: python -m pre_commit run -a || true
      - name: Fast pytest subset (markers)
        if: ${{ inputs['run-fast-tests'] }}
        shell: bash
        run: python -m pytest -p no:cacheprovider -o addopts="" -m "not slow and not e2e and not integration" -q
