name: Python Reusable Workflow

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system to run on'
        required: true
        type: string
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.11'
      diag:
        description: 'Enable diagnostics mode'
        required: false
        type: boolean
        default: false
      run-precommit:
        description: 'Run pre-commit hooks'
        required: false
        type: boolean
        default: true
      run-fast-tests:
        description: 'Run fast test suite'
        required: false
        type: boolean
        default: true

jobs:
  python-workflow:
    runs-on: ${{ inputs.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          
      - name: Diagnostics (if enabled)
        if: ${{ inputs.diag }}
        shell: bash
        run: |
          echo "=== DIAGNOSTIC INFO ==="
          python --version
          pip --version
          echo "OS: ${{ runner.os }}"
          echo "Python path: $(command -v python || where python)"
          echo "Pip cache dir: $(pip cache dir)"
          
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-lock.txt
          
      - name: Run pre-commit
        if: ${{ inputs.run-precommit }}
        shell: bash
        run: |
          pre-commit run --all-files
          
      - name: Run fast tests
        if: ${{ inputs.run-fast-tests }}
        shell: bash
        run: |
          python -m pytest -v -k "not slow and not e2e and not integration" --tb=short
