name: ci-fast-parity
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  fast-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/_python-reusable.yml
    with:
      os: ${{ matrix.os }}
      python-version: "3.11"
      run-precommit: true
      run-fast-tests: true