name: Fast Parity CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  fast-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/_python-reusable.yml
    with:
      os: ${{ matrix.os }}
      python-version: '3.11'
      diag: false
      run-precommit: true
      run-fast-tests: true
