name: cli-demo

on:
  workflow_dispatch:

jobs:
  run-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run CLI demo
        shell: pwsh
        run: pwsh -NoProfile -File scripts/bdr-demo.ps1
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: cli-demo-report
          path: examples/demo/output/report.json
