name: cli-pack
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build
        run: pip install build
      - name: Build wheel & sdist
        run: python -m build
      - name: Upload to Release (if release)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
      - name: Upload artifact (if manual)
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: cli-dist
          path: dist
