name: Docker Build & Test

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'docker-compose*.yml'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'Dockerfile'
      - 'docker-compose*.yml'
      - 'requirements.txt'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: bardirectoryrecon:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Image
      run: |
        docker run --rm bardirectoryrecon:test python -m pytest

    - name: Test Debug Configuration
      run: |
        docker-compose -f docker-compose.debug.yml config
        docker-compose -f docker-compose.debug.yml up -d
        docker-compose -f docker-compose.debug.yml logs
        docker-compose -f docker-compose.debug.yml down
