name: hygiene-audit
on:
  pull_request:
  workflow_dispatch:
jobs:
  audit:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt
      - name: Install deps
        shell: bash
        run: |
          python -m pip install -U pip
          if test -f requirements-lock.txt; then
            python -m pip install -r requirements-lock.txt
            python -m pip install -e .[dev] --no-deps || true
          else
            python -m pip install -e .[dev] || true
          fi
      - name: Pre-commit (all) to report
        shell: bash
        run: python -m pre_commit run -a || true
      - name: Mypy report
        shell: bash
        run: |
          python -m pip install mypy || true
          python -m mypy . || true
      - name: Detect-secrets audit
        shell: bash
        run: |
          python -m pip install detect-secrets || true
          detect-secrets scan > detect-secrets.out || true
      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hygiene-audit
          path: |
            .pre-commit-config.yaml
            detect-secrets.out
            **/.mypy.ini
            pyproject.toml
            **/mypy-report*.txt
