name: publish-testpypi
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install build & twine
        run: python -m pip install build twine
      - name: Build artifacts
        run: python -m build
      - name: Upload to TestPyPI (if secret present)
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
        run: |
          if [ -z "$TWINE_PASSWORD" ]; then
            echo "Secret missing; dry-run only."
          else
            python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
          fi