name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint & Type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install linting tools
        run: |
          pip install --upgrade pip
          pip install flake8 mypy

      - name: Run flake8
        run: flake8 .

      - name: Run mypy
        run: mypy .

  test:
    name: Install & (placeholder) Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            pytest --maxfail=1 --disable-warnings -q
          else
            echo "No tests directory; skipping."
          fi
